/////////////////////////////////////////////////////////////////////////////
// $Id: $
// <copyright file="AssemblyInfo.cs" company="James John McGuire">
// Copyright © 2016 - 2018 James John McGuire. All Rights Reserved.
// </copyright>
//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
/////////////////////////////////////////////////////////////////////////////

using System.Reflection;
using System.Resources;

[assembly: AssemblyTitle("FlickrStorage")]
[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("")]
[assembly: AssemblyProduct("James John McGuire")]
[assembly: AssemblyCopyright("Copyright © 2016 - 2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]
[assembly: NeutralResourcesLanguage("en-US")]

[assembly: AssemblyVersion("0.2.1.4")]
