/////////////////////////////////////////////////////////////////////////////
// <copyright file="DriveMapping.cs" company="James John McGuire">
// Copyright © 2017 - 2026 James John McGuire. All Rights Reserved.
// </copyright>
/////////////////////////////////////////////////////////////////////////////

namespace DigitalZenWorks.BackUp.Library;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using Microsoft.Extensions.FileSystemGlobbing;
using Newtonsoft.Json;

/// <summary>
/// DriveMapping custom class.
/// </summary>
public class DriveMapping
{
	private ICollection<Exclude> excludes = [];

	/// <summary>
	/// Initializes a new instance of the <see cref="DriveMapping"/> class
	/// using the specified settings.
	/// </summary>
	/// <remarks>Global excludes defined in the provided settings are
	/// processed to determine which items should be excluded from the drive
	/// mapping.</remarks>
	public DriveMapping()
	{
	}

	/// <summary>
	/// Gets or sets the local path property.
	/// </summary>
	/// <value>The local path property.</value>
	[JsonProperty("Path")]
	public string LocalPath { get; set; }

	/// <summary>
	/// Gets or sets the core shared parent folder id property.
	/// </summary>
	/// <value>The core shared parent folder id property.</value>
	public string DriveParentFolderId { get; set; }

	/// <summary>
	/// Gets excludes property.
	/// </summary>
	/// <value>Excludes property.</value>
	public ICollection<Exclude> Excludes
	{
		get { return excludes; }
	}

	/// <summary>
	/// Expands a collection of exclude patterns by resolving wildcard file
	/// paths into individual exclude entries.
	/// </summary>
	/// <remarks>Wildcard patterns are only expanded for file-type excludes
	/// whose paths contain the '*' character. Non-wildcard and non-file
	/// excludes are included in the result as-is.</remarks>
	/// <param name="excludes">A collection of exclude patterns, which may
	/// include entries with wildcard characters in their paths.</param>
	/// <returns>A collection containing the original exclude patterns and any
	/// additional excludes generated by expanding wildcard file paths. Returns
	/// an empty collection if the input collection is null.</returns>
	public static ICollection<Exclude> ExpandWildCardExcludes(
		ICollection<Exclude> excludes)
	{
		Collection<Exclude> expandedExcludes = [];

		if (excludes != null)
		{
			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.Path.Contains(
						'*', StringComparison.OrdinalIgnoreCase))
				{
					Collection<Exclude> newExcludes = ExpandWildCard(exclude);

					if (newExcludes.Count > 0)
					{
						foreach (Exclude newExclude in newExcludes)
						{
							expandedExcludes.Add(newExclude);
						}
					}
				}
				else
				{
					expandedExcludes.Add(exclude);
				}
			}
		}

		return expandedExcludes;
	}

	/// <summary>
	/// Expand excludes method.
	/// </summary>
	/// <returns>A list of expanded excludes.</returns>
	public ICollection<Exclude> ExpandExcludes()
	{
		if (excludes != null)
		{
			Collection<Exclude> expandedExcludes = [];

			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				exclude = ExpandExclude(LocalPath, exclude);
				expandedExcludes.Add(exclude);
			}

			excludes = ExpandWildCardExcludes(expandedExcludes);
		}

		return excludes;
	}

	private static Collection<Exclude> ExpandWildCard(Exclude originalExclude)
	{
		Collection<Exclude> newExcludes = [];

		string path = originalExclude.Path;

		if (path.Contains(
			'*', StringComparison.OrdinalIgnoreCase))
		{
			int index = path.IndexOf('*', StringComparison.OrdinalIgnoreCase);
			string pattern = path[index..];

			Matcher matcher = new();
			matcher.AddInclude(pattern);

			string directory = Path.GetDirectoryName(path);
			IEnumerable<string> matchingFiles =
				matcher.GetResultsInFullPath(directory);

			foreach (string match in matchingFiles)
			{
				Exclude exclude = new(match, originalExclude.KeepOnRemote);
				newExcludes.Add(exclude);
			}
		}

		return newExcludes;
	}

	private static Exclude ExpandExclude(string rootPath, Exclude exclude)
	{
		exclude.Path = Environment.ExpandEnvironmentVariables(exclude.Path);

		bool isQualified = Path.IsPathFullyQualified(exclude.Path);

		if (isQualified == false)
		{
			exclude.Path = Path.Combine(rootPath, exclude.Path);
		}

		exclude.Path = Path.GetFullPath(exclude.Path);

		return exclude;
	}
}
