/////////////////////////////////////////////////////////////////////////////
// <copyright file="DriveMapping.cs" company="James John McGuire">
// Copyright © 2017 - 2026 James John McGuire. All Rights Reserved.
// </copyright>
/////////////////////////////////////////////////////////////////////////////

namespace DigitalZenWorks.BackUp.Library;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using Microsoft.Extensions.FileSystemGlobbing;

/// <summary>
/// DriveMapping custom class.
/// </summary>
public class DriveMapping
{
	private List<Exclude> excludes = [];

	/// <summary>
	/// Initializes a new instance of the <see cref="DriveMapping"/> class
	/// using the specified settings.
	/// </summary>
	/// <remarks>Global excludes defined in the provided settings are
	/// processed to determine which items should be excluded from the drive
	/// mapping.</remarks>
	/// <param name="settings">The settings used to configure the drive
	/// mapping. If null, default settings are applied.</param>
	public DriveMapping(Settings settings = null)
	{
		if (settings != null)
		{
			AddGlobalExcludesTemplates(settings.GlobalExcludes);
		}
	}

	/// <summary>
	/// Gets or sets path property.
	/// </summary>
	/// <value>Path property.</value>
	public string Path { get; set; }

	/// <summary>
	/// Gets or sets the core shared parent folder id property.
	/// </summary>
	/// <value>The core shared parent folder id property.</value>
	public string DriveParentFolderId { get; set; }

	/// <summary>
	/// Gets excludes property.
	/// </summary>
	/// <value>Excludes property.</value>
	public IList<Exclude> Excludes
	{
		get { return excludes; }
	}

	/// <summary>
	/// Gets the global excludes templates.
	/// </summary>
	/// <value>The global excludes templates.</value>
	public ICollection<string> GlobalExcludesTemplates { get; } = [];

	/// <summary>
	/// Expand global excludes method.
	/// </summary>
	/// <param name="rootPath">The root path.</param>
	/// <param name="excludes">The current set of includes.</param>
	/// <returns>A list of expanded excludes.</returns>
	public static IList<Exclude> ExpandGlobalExcludes(
		string rootPath, IList<Exclude> excludes)
	{
		List<Exclude> expandedExcludes = null;

		if (excludes != null)
		{
			expandedExcludes = [];

			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType == ExcludeType.Global)
				{
					exclude = ExpandExclude(rootPath, exclude);
				}

				if (exclude.ExcludeType == ExcludeType.File &&
					exclude.Path.Contains(
						'*', StringComparison.OrdinalIgnoreCase))
				{
					List<Exclude> newExcludes = ExpandWildCard(exclude.Path);

					if (newExcludes.Count > 0)
					{
						expandedExcludes.AddRange(newExcludes);
					}
				}
				else
				{
					expandedExcludes.Add(exclude);
				}
			}
		}

		return expandedExcludes;
	}

	/// <summary>
	/// Expands a collection of exclude patterns by resolving wildcard file
	/// paths into individual exclude entries.
	/// </summary>
	/// <remarks>Wildcard patterns are only expanded for file-type excludes
	/// whose paths contain the '*' character. Non-wildcard and non-file
	/// excludes are included in the result as-is.</remarks>
	/// <param name="path">The base directory path used to resolve wildcard
	/// patterns within the exclude entries.</param>
	/// <param name="excludes">A collection of exclude patterns, which may
	/// include entries with wildcard characters in their paths.</param>
	/// <returns>A collection containing the original exclude patterns and any
	/// additional excludes generated by expanding wildcard file paths. Returns
	/// an empty collection if the input collection is null.</returns>
	public static ICollection<Exclude> ExpandWildCardExcludes(
		string path, ICollection<Exclude> excludes)
	{
		Collection<Exclude> expandedExcludes = [];

		if (excludes != null)
		{
			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType == ExcludeType.File &&
					exclude.Path.Contains(
						'*', StringComparison.OrdinalIgnoreCase))
				{
					List<Exclude> newExcludes = ExpandWildCard(exclude.Path);

					if (newExcludes.Count > 0)
					{
						foreach (Exclude newExclude in newExcludes)
						{
							expandedExcludes.Add(newExclude);
						}
					}
				}
				else
				{
					expandedExcludes.Add(exclude);
				}
			}
		}

		return expandedExcludes;
	}

	/// <summary>
	/// Adds the specified global exclusion names to the collection, ensuring
	/// that only unique exclusions are included.
	/// </summary>
	/// <remarks>If the provided list is null, no exclusions are added.
	/// Duplicate exclusion names are ignored, and only unique names are
	/// stored.</remarks>
	/// <param name="globalExcludesTemplates">A read-only list of exclusion
	/// names to add as global exclusions. Each name must be unique and cannot
	/// be null. </param>
	public void AddGlobalExcludesTemplates(
		IReadOnlyCollection<string> globalExcludesTemplates)
	{
		if (globalExcludesTemplates != null)
		{
			foreach (string excludeName in globalExcludesTemplates)
			{
				bool exists = GlobalExcludesTemplates.Any(e => e.Equals(
					excludeName, StringComparison.OrdinalIgnoreCase));

				if (exists == false)
				{
					GlobalExcludesTemplates.Add(excludeName);
				}
			}
		}
	}

	/// <summary>
	/// Expand excludes method.
	/// </summary>
	/// <returns>A list of expanded excludes.</returns>
	public IList<Exclude> ExpandExcludes()
	{
		if (excludes != null)
		{
			List<Exclude> expandedExcludes = [];

			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType != ExcludeType.Global)
				{
					exclude = ExpandExclude(Path, exclude);
				}

				if (exclude.ExcludeType == ExcludeType.File &&
					exclude.Path.Contains(
						'*', StringComparison.OrdinalIgnoreCase))
				{
					List<Exclude> newExcludes = ExpandWildCard(exclude.Path);

					if (newExcludes.Count > 0)
					{
						expandedExcludes.AddRange(newExcludes);
					}
				}
				else
				{
					expandedExcludes.Add(exclude);
				}
			}

			excludes = expandedExcludes;
		}

		return excludes;
	}

	private static List<Exclude> ExpandWildCard(string path)
	{
		List<Exclude> newExcludes = [];

		if (path.Contains(
			'*', StringComparison.OrdinalIgnoreCase))
		{
			int index = path.IndexOf('*', StringComparison.OrdinalIgnoreCase);
			string pattern = path[index..];

			Matcher matcher = new();
			matcher.AddInclude(pattern);

			string directory = System.IO.Path.GetDirectoryName(path);
			IEnumerable<string> matchingFiles =
				matcher.GetResultsInFullPath(directory);

			foreach (string match in matchingFiles)
			{
				Exclude exclude = new(match, ExcludeType.File);
				newExcludes.Add(exclude);
			}
		}

		return newExcludes;
	}

	private static Exclude ExpandExclude(string rootPath, Exclude exclude)
	{
		exclude.Path = Environment.ExpandEnvironmentVariables(exclude.Path);

		bool isQualified = System.IO.Path.IsPathFullyQualified(exclude.Path);

		if (isQualified == false)
		{
			exclude.Path = System.IO.Path.Combine(rootPath, exclude.Path);
		}

		exclude.Path = System.IO.Path.GetFullPath(exclude.Path);

		return exclude;
	}
}
