/////////////////////////////////////////////////////////////////////////////
// <copyright file="DriveMapping.cs" company="James John McGuire">
// Copyright © 2017 - 2026 James John McGuire. All Rights Reserved.
// </copyright>
/////////////////////////////////////////////////////////////////////////////

namespace DigitalZenWorks.BackUp.Library;

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Linq;
using Microsoft.Extensions.FileSystemGlobbing;
using Newtonsoft.Json;

/// <summary>
/// DriveMapping custom class.
/// </summary>
public class DriveMapping
{
	private ICollection<Exclude> excludes = [];

	/// <summary>
	/// Initializes a new instance of the <see cref="DriveMapping"/> class
	/// using the specified settings.
	/// </summary>
	/// <remarks>Global excludes defined in the provided settings are
	/// processed to determine which items should be excluded from the drive
	/// mapping.</remarks>
	/// <param name="settings">The settings used to configure the drive
	/// mapping. If null, default settings are applied.</param>
	public DriveMapping(Settings settings = null)
	{
		if (settings != null)
		{
			AddGlobalExcludesTemplates(settings.GlobalExcludes);
		}
	}

	/// <summary>
	/// Gets or sets the local path property.
	/// </summary>
	/// <value>The local path property.</value>
	[JsonProperty("Path")]
	public string LocalPath { get; set; }

	/// <summary>
	/// Gets or sets the core shared parent folder id property.
	/// </summary>
	/// <value>The core shared parent folder id property.</value>
	public string DriveParentFolderId { get; set; }

	/// <summary>
	/// Gets excludes property.
	/// </summary>
	/// <value>Excludes property.</value>
	public ICollection<Exclude> Excludes
	{
		get { return excludes; }
	}

	/// <summary>
	/// Gets the global excludes templates.
	/// </summary>
	/// <value>The global excludes templates.</value>
	public ICollection<string> GlobalExcludesTemplates { get; } = [];

	/// <summary>
	/// Expands global excludes relative to the current traversal directory,
	/// returning a new list with all global excludes resolved to fully
	/// qualified paths.
	/// </summary>
	/// <remarks>
	/// This method is intended to be called once per directory as the
	/// traversal descends the tree. Each global exclude — typically a
	/// relative name such as "obj" or "node_modules" — is resolved to a
	/// fully qualified path by combining it with the current directory path.
	/// Non-global excludes are passed through unchanged.
	///
	/// Wildcard excludes should be fully expanded to concrete paths before
	/// this method is called. See <see cref="ExpandWildCardExcludes"/> for
	/// wildcard expansion, which is performed once per account prior to
	/// traversal.
	///
	/// If <paramref name="excludes"/> is null, null is returned. If it is
	/// empty, an empty list is returned.
	/// </remarks>
	/// <param name="currentPath">The fully qualified path of the directory
	/// currently being traversed. Global excludes are resolved relative to
	/// this path.</param>
	/// <param name="excludes">The current set of excludes to process.
	/// May be null.</param>
	/// <returns>A new collection of excludes with global entries resolved to
	/// fully qualified paths, or null if <paramref name="excludes"/> is
	/// null.</returns>
	public static ICollection<Exclude> ExpandGlobalExcludes(
		string currentPath, ICollection<Exclude> excludes)
	{
		Collection<Exclude> expandedExcludes = null;

		if (excludes != null)
		{
			expandedExcludes = [];

			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType == ExcludeType.Global)
				{
					exclude = ExpandExclude(currentPath, exclude);
				}

				expandedExcludes.Add(exclude);
			}
		}

		return expandedExcludes;
	}

	/// <summary>
	/// Expands a collection of exclude patterns by resolving wildcard file
	/// paths into individual exclude entries.
	/// </summary>
	/// <remarks>Wildcard patterns are only expanded for file-type excludes
	/// whose paths contain the '*' character. Non-wildcard and non-file
	/// excludes are included in the result as-is.</remarks>
	/// <param name="excludes">A collection of exclude patterns, which may
	/// include entries with wildcard characters in their paths.</param>
	/// <returns>A collection containing the original exclude patterns and any
	/// additional excludes generated by expanding wildcard file paths. Returns
	/// an empty collection if the input collection is null.</returns>
	public static ICollection<Exclude> ExpandWildCardExcludes(
		ICollection<Exclude> excludes)
	{
		Collection<Exclude> expandedExcludes = [];

		if (excludes != null)
		{
			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType == ExcludeType.File &&
					exclude.Path.Contains(
						'*', StringComparison.OrdinalIgnoreCase))
				{
					Collection<Exclude> newExcludes =
						ExpandWildCard(exclude.Path);

					if (newExcludes.Count > 0)
					{
						foreach (Exclude newExclude in newExcludes)
						{
							expandedExcludes.Add(newExclude);
						}
					}
				}
				else
				{
					expandedExcludes.Add(exclude);
				}
			}
		}

		return expandedExcludes;
	}

	/// <summary>
	/// Adds the specified global exclusion names to the collection, ensuring
	/// that only unique exclusions are included.
	/// </summary>
	/// <remarks>If the provided list is null, no exclusions are added.
	/// Duplicate exclusion names are ignored, and only unique names are
	/// stored.</remarks>
	/// <param name="globalExcludesTemplates">A read-only list of exclusion
	/// names to add as global exclusions. Each name must be unique and cannot
	/// be null. </param>
	public void AddGlobalExcludesTemplates(
		IReadOnlyCollection<string> globalExcludesTemplates)
	{
		if (globalExcludesTemplates != null)
		{
			foreach (string excludeName in globalExcludesTemplates)
			{
				bool exists = GlobalExcludesTemplates.Any(e => e.Equals(
					excludeName, StringComparison.OrdinalIgnoreCase));

				if (exists == false)
				{
					GlobalExcludesTemplates.Add(excludeName);
				}
			}
		}
	}

	/// <summary>
	/// Expand excludes method.
	/// </summary>
	/// <returns>A list of expanded excludes.</returns>
	public ICollection<Exclude> ExpandExcludes()
	{
		if (excludes != null)
		{
			Collection<Exclude> expandedExcludes = [];

			foreach (Exclude temporaryExclude in excludes)
			{
				Exclude exclude = temporaryExclude;

				if (exclude.ExcludeType != ExcludeType.Global)
				{
					exclude = ExpandExclude(LocalPath, exclude);
					expandedExcludes.Add(exclude);
				}
			}

			excludes = ExpandWildCardExcludes(expandedExcludes);
		}

		return excludes;
	}

	private static Collection<Exclude> ExpandWildCard(string path)
	{
		Collection<Exclude> newExcludes = [];

		if (path.Contains(
			'*', StringComparison.OrdinalIgnoreCase))
		{
			int index = path.IndexOf('*', StringComparison.OrdinalIgnoreCase);
			string pattern = path[index..];

			Matcher matcher = new();
			matcher.AddInclude(pattern);

			string directory = Path.GetDirectoryName(path);
			IEnumerable<string> matchingFiles =
				matcher.GetResultsInFullPath(directory);

			foreach (string match in matchingFiles)
			{
				Exclude exclude = new(match, ExcludeType.File);
				newExcludes.Add(exclude);
			}
		}

		return newExcludes;
	}

	private static Exclude ExpandExclude(string rootPath, Exclude exclude)
	{
		exclude.Path = Environment.ExpandEnvironmentVariables(exclude.Path);

		bool isQualified = Path.IsPathFullyQualified(exclude.Path);

		if (isQualified == false)
		{
			exclude.Path = Path.Combine(rootPath, exclude.Path);
		}

		exclude.Path = Path.GetFullPath(exclude.Path);

		return exclude;
	}
}
